### ISSUE TITLE
Could you please provide 64bit DLL?

### ISSUE THREAD

**Issue by jooyoungseo** [mpcabd/PyNPP#5]
Hello,

Thank you very much for making this great NPP plugins.
I was wondering if you could provide users with PyNPP compiled for 64bit DLL as well.
The current version is not compatible with 64-bit NPP.
Many thanks.

**Comment by Danixu** [comment]
Hello,

I don't know why the creator has not made an x64 version, because all work is done. I've compiled the latest version in x64 and looks like works on my Notepadd++:
https://github.com/Danixu/PyNPP/releases

Greetings!

**Comment by mpcabd** [comment]
Could you guys test this fresh release: https://github.com/mpcabd/PyNPP/releases/tag/v1.2.1-1

I couldn't test it myself unfortunately.

**Comment by Danixu** [comment]
I've installed the version I've compiled, but I'll give a try to yours to see.
Was to much time searching, and was easier to download visual studio and compile 😋

**Comment by Danixu** [comment]
Hello!!, looks like is working fine.

Thanks!!
