### ISSUE TITLE
Adapting Python Script script 

### ISSUE THREAD

**Issue by chopinesque** [mpcabd/PyNPP#6]
Hi, thank you for your plugin. I updated NP++ and I found your plugin. I used to use the PythonScript plugin (seems to be no longer available via NP++ Plugin Admin), open a file, then select the script that will run on that file. Is it possible to do that with your plugin?

**Comment by mpcabd** [comment]
Hi,

Currently it's not really possible, this plugin just does `python.exe [OPTIONS] path\to\file` nothing more.

It can be of course extended to do so, but unfortunately I don't have the time or the resources (Windows machines) to do that any more, feel free to submit a merge request with the needed change.
